### ISSUE TITLE
increase default docker memory and tomcat memory

### ISSUE THREAD

**Issue by nathandunn** [GMOD/docker-apollo#42]
- [ ] increase tomcat memory to be 2 GB max, 512MB min
- [ ] instructions for default docker memory, etc.

Notes:

https://stackoverflow.com/questions/29923531/how-to-set-java-heap-size-xms-xmx-inside-docker-container <https://stackoverflow.com/questions/29923531/how-to-set-java-heap-size-xms-xmx-inside-docker-container>

Upload is really slow.

**Comment by nathandunn** [comment]
Memory lockup is here:

![image](https://user-images.githubusercontent.com/751274/58636391-32d92700-82be-11e9-97fa-a4514ef66b4e.png)

**Comment by nathandunn** [comment]
```
*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message can't create byte arrau at JPLISAgent.c line: 813
Exception in thread "PostgreSQL-JDBC-SharedTimer-1" java.lang.OutOfMemoryError: Java heap space
	at java.io.BufferedOutputStream.<init>(BufferedOutputStream.java:76)
	at org.postgresql.core.PGStream.changeSocket(PGStream.java:122)
	at org.postgresql.core.PGStream.<init>(PGStream.java:62)
	at org.postgresql.core.QueryExecutorBase.sendQueryCancel(QueryExecutorBase.java:158)
	at org.postgresql.jdbc.PgConnection.cancelQuery(PgConnection.java:1049)
	at org.postgresql.jdbc.PgStatement.cancel(PgStatement.java:814)
	at org.postgresql.jdbc.PgStatement$1.run(PgStatement.java:882)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

**Comment by nathandunn** [comment]
I think it was inadvertently running to many dud processes in the background and subsequent docker files have fixed this.
